fix: set the Dockerfile to call an entrypoint instead of hard-coding shellscripts into the here-docs

diff --git a/.config/nvim/other-apps/ipynb/Dockerfile.headers b/.config/nvim/other-apps/ipynb/Dockerfile.headers
--- a/.config/nvim/other-apps/ipynb/Dockerfile.headers
+++ b/.config/nvim/other-apps/ipynb/Dockerfile.headers
@@ -12,99 +12,17 @@ ENV NVIM_USER="nvim"
 
 RUN <<EOF
 
-apk upgrade && apk update && \
-    apk add --no-cache build-base linux-headers \
-        neovim luarocks git nodejs npm \
-        libx11-dev xorgproto \
-        clang meson ninja cmake pkgconfig ethtool imagemagick
+TARGET_SCRIPT_PATH="/scripts/jupynvim.sh"
 
+build_routine() {
+    if ! ( MODE="build" . "${TARGET_SCRIPT_PATH}" ); then
+    echo "|> [ERROR]: could not run the [build] function of the [TARGET_SCRIPT_PATH]. Exiting now..."
+    return 1
 
-(
-cat <<HMM
-http://dl-cdn.alpinelinux.org/alpine/edge/main
-http://dl-cdn.alpinelinux.org/alpine/edge/community
-http://dl-cdn.alpinelinux.org/alpine/edge/testing
-HMM
-) > /etc/apk/repositories
-
-apk add libxext libxext-dev libxres-dev
-
-#
-
-EOF
-
-
-RUN <<EOF
-set -e
-
-NVIM_USER="nvim"
-
-# Copy files to /test beforehand
-mkdir -p /tests/
-chown -R $NVIM_USER:$NVIM_USER /tests/
-
-
-# set python provider
-addgroup -g 1000 -S "${NVIM_USER}" && \
-adduser -s /bin/sh -u 1000 -G "${NVIM_USER}" \
-    -h "/home/${NVIM_USER}" -D "${NVIM_USER}" && \
-
-mkdir -p /home/"${NVIM_USER}/.config/nvim/" && \
-chown -R "$NVIM_USER:$NVIM_USER" /home/"${NVIM_USER}"/.config && \
-cd /home/"${NVIM_USER}/.config/nvim/" && \
-
-npm install -g tree-sitter-cli && \
-
-
-su "${NVIM_USER}" -c '
-export PATH=$HOME/.local/bin/:$PATH && \
-pip3 install --user --upgrade pip virtualenv --break-system-packages && \
-virtualenv "$HOME"/.config/nvim/venv_nvim/neovim3 && source ./venv_nvim/neovim3/bin/activate && \
-python3 -m ensurepip --default-pip && \
-pip3 install --no-cache-dir -r /tests/requirements.txt && \
-
-
-git clone https://github.com/deomorxsy/deorice.git
-cp -r "$HOME"/.config/nvim/deorice/.config/* "$HOME"/.config/
-
-cp ./deorice/.config/nvim/other-apps/ipynb/treesitter.lua ./after/plugin/treesitter.lua
-cp ./deorice/.config/nvim/other-apps/ipynb/lazy.lua ./lua/config/lazy.lua
-
-rm ./after/plugin/lean.lua
-
-
-NOTE=/tests/pyarrow_livy_test.ipynb
-
-# source ./venv_nvim/neovim3/bin/activate
-
-nvim --headless \
-    -c "lua print('Lazy syncing + jupytext test…')" \
-    -c 'Lazy sync' \
-    -c 'UpdateRemotePlugins' \
-    -c "edit $NOTE" \
-    -c 'write' \
-    -c 'quitall'
-
-# nvim --headless -u NONE -c "luafile $dir/hullo.lua" -c ":qa" >> /test/test_result_"$(basename "$dir")"_.txt 2>&1
-# nvim --headless -u NONE -c "lua os.execute('mkdir -p ./other-apps/ipynb/')" -c ":qa"
-
-# -u NONE, which disables all plugins and configuration
-# --no-plugin is implied by -u NONE
-nvim --headless -c "lua print('Setting up Magma...')" \
-    -c ":Lazy sync" \
-    -c ":UpdateRemotePlugins" \
-    -c ":MagmaInit python3" \
-    -c ":qa"
-
-deactivate
-
-'
-# pynvim
-
-# set node provider
-# todo: set user for local npm install
-npm install -g nvim
-npm install -g tree-sitter-cli
+    fi
+    echo "|> [PASS]: successfully ran the [build] function of the [TARGET_SCRIPT_PATH]. Proceeding..."
+}
+build_routine
 
 
 EOF
@@ -138,7 +56,10 @@ done
 su "${NVIM_USER}" && nvim_tests
 EOF
 
-ENTRYPOINT [ "nvim", "--headless", "-c" , "'so'", "-c", "'PackerSync'", " "${HOME}/.config/nvim/lua/user/packer.lua" " ]
+
+ENTRYPOINT ["MODE='entrypoint' . ./scripts/jupynvim.sh"]
+
+#ENTRYPOINT [ "nvim", "--headless", "-c" , "'so'", "-c", "'PackerSync'", "'${HOME}/.config/nvim/lua/user/packer.lua'" ]
 
 
 # =========
